; AutoCopyCoDeSys.ini
; Version: 2.0
; Author: Joerg Wohlhueter

;Version: 2.1
;Date: 18/11/2014
;Author: Donal Lyne
;Description: Modified functionality of ReplacementTexts\ProjectName to allow for blank entry.

;Version: 2.2
;Date: 16/02/2015
;Author: Donal Lyne
;Description: Modified to use robocopy

[ReplacementTexts]
;Root is Location of project folder.  Root is a required entry
Root=D:\Prj
;Leave ProjectName blank and the software will automatically figure out project folder.  
;ProjectName is a required entry (even if left blank)
ProjectName=RT1436_37
;Further text items to be replaced can be added here.
;Use this path on Laptops
;TempDir=C:\Users\user\AppData\Local\Temp\CoDeSys
;Use this path on HP rp5800 PCs
;C:\Users\user4\AppData\Local\Temp\CoDeSys
TempDir=C:\Users\user\AppData\Local\Temp\CoDeSys
EncryptedFolderNumber=0FF8C8B74C492E93C50D6A162B3020B4__ff09a243-ad15-441f-90f7-e88599aff0ca
RemotePCPrjLocation=\\1.92.10.80\d\Prj
;SecondRemotePCPrjLocation=\\1.92.10.81\d\Prj

[SourcePaths]
;Copy 1 of the sections below, and remove the semi-colons from the start of the line to activate 

;Section A: on crane PC with ABB PLC, use following lines...
;These lines copy folders to the CopiedCodeSys folder if Automation Builder is 1.0.1
;Source1=[Root]\[ProjectName]\[ProjectName] Software\[ProjectName]__AC500_PM592_ETH_V2_3__AC500_[ProjectName]

;Use the following line with Automation Builder 1.1
;Source1=[TempDir]\[EncryptedFolderNumber]

;These lines are for installations with a CoDeSys HMI touch screen
;Source2=[Root]\[ProjectName]\[ProjectName] Software\Library
;Source3=[Root]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Source4=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys
;Source5=[Root]\[ProjectName]\[ProjectName] Software\Touchscreen

;These lines are for installations with a 2nd CoDeSys HMI touch screen
;Source6=[Root]\[ProjectName]\[ProjectName] Software\Library
;Source7=[Root]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Source8=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys
;Source9=[Root]\[ProjectName]\[ProjectName] Software\Touchscreen

;Section B: On crane PC with Non-ABB PLC with CoDeSys HMI touch screen, use the following lines...
;Source1=[Root]\[ProjectName]\[ProjectName] Software
;Source2=[Root]\[ProjectName]\[ProjectName] Software\Library
;Source3=[Root]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Source4=[Root]\[ProjectName]\[ProjectName] Software\Touchscreen


;In use
Source1=[TempDir]\[EncryptedFolderNumber]
;Source1=[Root]\[ProjectName]\[ProjectName] Software\[ProjectName]__AC500_PM592_ETH_V2_3__AC500_[ProjectName]
;These lines are for installations with a CoDeSys HMI touch screen
Source2=[Root]\[ProjectName]\[ProjectName] Software\Library
Source3=[Root]\[ProjectName]\[ProjectName] Software\Codesys Visu
Source4=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys
Source5=[Root]\[ProjectName]\[ProjectName] Software\Touchscreen


[DestinationPaths]
;Copy 1 of the sections below, and remove the semi-colons from the start of the line to activate 

;Section A: On crane PC with ABB PLC, use following lines...
;Destination1=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys

;These lines are for installations with a CoDeSys HMI touchscreen
;Destination2=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Library
;Destination3=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Destination4=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software
;Destination5=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Touchscreen
;These lines are for installations with a 2nd CoDeSys HMI touch screen
;Destination6=[SecondRemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Library
;Destination7=[SecondRemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Destination8=[SecondRemotePCPrjLocation]\[ProjectName]\[ProjectName] Software
;Destination9=[SecondRemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Touchscreen


;Section B: On crane PC with Non-ABB PLC with CoDeSys HMI touch screen, use the following lines...
;Destination1=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software
;Destination2=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Library
;Destination3=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Codesys Visu
;Destination4=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Touchscreen

;In use
Destination1=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys
;These lines are for installations with a CoDeSys HMI touchscreen
Destination2=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Library
Destination3=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Codesys Visu
Destination4=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software
Destination5=[RemotePCPrjLocation]\[ProjectName]\[ProjectName] Software\Touchscreen

[HiddenDestinationFilesAndFolders]
1=[Root]\[ProjectName]\[ProjectName] Software\CopiedCoDeSys

[Settings]
;See https://technet.microsoft.com/en-us/library/cc733145.aspx
;RobocopyParameters=/mir /r:2 /w:2 /lev:1 /xf *.asd /xo

;In use
RobocopyParameters=/mir /r:2 /w:2 /lev:1 /xf *.asd /xo