[CoDeSysHMI]
LibraryDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3\Library
CompileDir=C:\ProgramData\CoDeSys V2.3\Compile
UploadDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3\Upload
ProjectsDir=E:\Test\V23\m.asef\Beckhoff\SC-31894_\Paride D'Alessandro\2015_06_16\150616_ProgettoTME\UTE\SCHEMI\875-13\software\Beckhoff\15_02_11
;VisuMaxNumOfOpenChildWindows - This paramter must be big enough to cater for all Drivers HMI screens
VisuMaxNumOfOpenChildWindows=20
;VisusToOpenOnStartup - Every Drivers HMI screen should be added to this semi-colon separated list.  Each screen in this section is opened on HMI runtime startup.  Get the names from the CoDeSYs Project\Visualisation section
VisusToOpenOnStartup=VIS_ERRORS_1;VIS_ERRORS_2;VIS_ERRORS_3;VIS_LEGEND_Control_Panel;VIS_LEGEND_MAIN_SCREEN;VIS_LEGEND_SPREADER;VIS_ADMINISTRATION;VIS_CLEAN_MODE;VIS_DRIVERSHELP;VIS_SPREADER;VIS_TYRE_PRESSURE
;VisuNoScrollBars - By setting this parameter to Yes, scrollbars are forced off.
VisuNoScrollBars=Yes
COM_PORT=2
BaudRate=19200
StopBits=1
Parity=0
VisFontSize=-13
VisFontWeight=400
VisFontItalic=No
VisFontUnderline=No
VisFontStrikeOut=No
VisFontCharSet=0
VisFontFace=MS Sans Serif
VisFontColor=0
InputLogging=No
LogFile=
VisCompile=No
WindowShowCmd=1
WindowLeft=-3
WindowTop=-26
WindowRight=1695
WindowBottom=1065
StepHeight=4
StepWidth=6
CommentWidth=6
SFCUseIECSteps=No
MinCommentSize=0
MaxCommentSize=4
LDCommentSize=1
LDVarSize=1
ContactsWithComments=No
NetworkBreaks=No
ReplaceAddressWithSymbol=No
ShowAddress=No
SetContactComment=No
ShowVariableDefinitionPerRung=No
WatchPercent=50
MultiVariableDist=200
Toolbar=Yes
Statusbar=Yes
Size=-12
FaceWeight=400
Italic=No
CharSet=0
Face=Arial
DisplayPrinterBorders=No
F4IgnoresWarnings=No
MDIInterface=Yes
TableWatchMan=No
RectMode=0
DisplayMode=1
NoMonitoringOfComplexTypes=No
ShowPOUBitmaps=Yes
ProjectInfoAuto=No
Autoformat=Yes
Autocomponent=Yes
Autodeclare=Yes
POULanguage=ST
XMLEncoding=ISO-8859-1
Autoload=Yes
SaveBeforeCompile=No
TabWidth=4
ObjectInOwnFile=No
UserName=
UserInitals=
UserCompany=
VisuDir=
IOConfigDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3\Library\PLCCONF\
ImportExportDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
DocuframeDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
MergeDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
CompareDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
TraceDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
WatchDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
SimaticDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
NewWithTemplateDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
Backup=No
SaveENICredentials=Yes
ColorNumbers=12632256
ColorBreakPos=8355711
ColorBreakPoint=16776960
ColorBreakCurrent=255
ColorFlow=65280
ColorMonitor=16711680
ColorSnapShot=16711935
Project0=E:\Test\V23\m.asef\Beckhoff\SC-31894_\Paride D'Alessandro\2015_06_16\150616_ProgettoTME\UTE\SCHEMI\875-13\software\Beckhoff\15_02_11\Kenos60V011_Test2.pro
Project1=E:\Projekte\Customers\Beckhoff\Ismail Güler\2015_03_31\Deneme\Users\OsmanK\Desktop\Dosyalar\YikamaHatti_gazdolum\Deneme_ms.pro
Project2=E:\Test\V357\CDS-29656\test.pro
ShowGrid=Yes
EnableGrid=Yes
AutoScroll=Yes
ShowNumbers=Yes
KeypadHideSpecialCharacters=No
HideMinMaxIfNotConfigured=No
GridSize=10
Zoom=100
ReferenceWithoutOffset=No
WebVisuScaleCorrection=No
BestFit=Yes
WithBitmap=No
DefaultGateway=150100000100000008010000BA04BB046C6F63616C686F7374006703DA98B87610000000B4FB120000000000E0114B084800670360016703004F4F084004670374D912002CD9120018DB120050DA120015E10C7727828100FEFFFFFF772F1077122E1077B4FB1200110100000000000000000000B4FB1200110100000000000001000000404F4F08F4D91200782C1077484F4F08B4FB120000000000404F4F0808DA1200AE9C6A0318DB12005502F300FFFFFFFF0000000080C357086CDA12000200000000000000180000001101000060DA1200B4FB1200110100000000000010000000B4FB12001101000000000000246EE500D8B45201FFFFFFFF18DB1200246EE500F0B45201FFFFFFFF24DB12003D13E50000
DefaultDevice=200100000000000041B1F09181FAD311AC4800105A4AB20E0800000000000000000000005463702F497020284C6576656C203220526F757465290044656E656D655F6D732E70726F00276C6F63616C686F73742720FC626572205463702F49705F003353205463702F4970204C6576656C203220526F7574657220447269766572000400000035000000E9030000416464726573730049502061646472657373206F7220686F73746E616D65000A0000006C6F63616C686F73740014000000E8030000506F7274000011000000B0041A000000FC03000054617267657449640000120000000000000037000000640000004D6F746F726F6C6120627974656F7264657200000F0000000000000002000000000000004E6F000100000059657300
Project3=E:\Test\V357\CDS-29656\Visu_MLD_1G.pro
DefaultWaitTime=2200
DownloadWaitTime=20000
Project4=H:\Support\Work\JIRA\Attachments\CDS\CDS-29656\Visu_MLD_1G.pro
Project5=E:\Test\V357\CDS-21435\WatchWindow.pro
DeclTables=No
Autosave=Yes
AutosaveInterval=10
Language=English
SFCDispAttributes=2
[Log]
SeparateDir=No
LogDir=C:\Program Files (x86)\3S Software\CoDeSys V2.3
MaxSessions=50
Active=No
FilterUserActions=Yes
FilterInternalActions=Yes
FilterStatusChanges=Yes
FilterExceptions=Yes
